"""Convert the INT8 TFLite model into a C header for TFLite Micro.

Usage:
    py deploy/tflite/export_model_header.py            # uses models/phase5_cnn_int8.tflite
    py deploy/tflite/export_model_header.py --model path/to/model.tflite

Writes deploy/esp32/CardioEdgeAI/model.h containing the model bytes as a
`const unsigned char cardioedge_model_data[]` array plus its length —
the format the TensorFlowLite_ESP32 Arduino library expects.
"""
import argparse
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_MODEL = REPO / "models" / "phase5_cnn_int8.tflite"
OUT = REPO / "deploy" / "esp32" / "CardioEdgeAI" / "model.h"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model", type=Path, default=DEFAULT_MODEL)
    args = parser.parse_args()

    blob = args.model.read_bytes()
    OUT.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "// Auto-generated by deploy/tflite/export_model_header.py",
        f"// source: {args.model.name} ({len(blob)} bytes)",
        "#ifndef CARDIOEDGE_MODEL_H_", "#define CARDIOEDGE_MODEL_H_",
        "",
        "alignas(16) const unsigned char cardioedge_model_data[] = {",
    ]
    for i in range(0, len(blob), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in blob[i:i + 12])
        lines.append("  " + chunk + ",")
    lines += [
        "};",
        f"const unsigned int cardioedge_model_len = {len(blob)};",
        "",
        "#endif  // CARDIOEDGE_MODEL_H_",
    ]
    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT} ({len(blob)} model bytes)")


if __name__ == "__main__":
    main()
